site_name: Dr. Clint Steed
theme:
  name: material
markdown_extensions:
  - footnotes
plugins:
  - search
  - tags
  - htmlproofer:
      raise_error_excludes:
        403: ['*']
        404: ['*']
        999: ['*']

