name: deploy on push
run-name: ${{ github.actor }} is testing actions
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing"

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - run: mkdir -p ./docs/deploy
      - run: echo "The branch is ${{ github.ref }} by ${{ github.actor }}" >> ./docs/deploy/info.md
      - run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - run: echo "${{ env.MY_DATE }}" >> ./docs/deploy/info.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install mkdocs mkdocs-material mkdocs-htmlproofer-plugin

      - name: Build and validate documentation
        run: |
          source .venv/bin/activate
          mkdocs build --strict

  deploy-gh:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install mkdocs mkdocs-material mkdocs-htmlproofer-plugin

      - name: Deploy documentation
        run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force
